today/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import All,Feras
from django.conf.urls import url
app_name='today'
urlpatterns = [
url(r'^all/$',All,name='all'),
url(r'^feras/$',Feras,name='feras'),
]

week/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('today.urls',namespace='week')),
]

today/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
# Create your models here.
class Post(models.Model):
    name=models.ForeignKey(User,on_delete=models.CASCADE)
    title=models.CharField(max_length=15)
    content=RichTextField()
    active =models.BooleanField(default=True)

    def __str__(self):
        return self.title

today/views.py
from django.shortcuts import render
from .models import Post
from django.http import HttpResponse
# Create your views here.
def All(request):
    all=Post.objects.filter(title='django')
    context={'all':all,
             'title':'feras'}
    return render(request,'today/all.html',context)
def Feras(request):
    return render(request,'today/feras.html')

today/templates/today/all.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>{{title}}</title>
</head>
<body>
{% for i in all %}
{{i.title}}
<br>
{{i.content|safe}}
<br>
<hr>
{% endfor %}
<img class= "rounded-circle" src="{% static 'today/img/1.jpg' %}" width="100px">
<img class= "rounded-circle" src="{% static 'today/img/1.jpg' %}" width="100px">
<img class= "rounded-circle" src="{% static 'today/img/1.jpg' %}" width="100px">
</body>
</html>

today/templates/today/feras.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">

    <title></title>
</head>
<body>
<h1>feras</h1><br>
<a href="{% url 'week:all' %}">All</a>
</body>
</html>